[project]
name = "proyecto-ingenieria-dato"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Santiago Lillo Macías", email = "santilillomacias@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]

[project.scripts]
proyecto-ingenieria-dato = "proyecto_ingenieria_dato:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=6.31.0",
]
